language: python
python:
  - "2.7"
before_install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install pycodestyle"
install:
  - "python setup.py install"
script:
  - "pycodestyle"
  - "coverage run --source=sniffer setup.py test"
after_success:
  coveralls
